### ISSUE TITLE
Errors when running on other cuda devices

### ISSUE THREAD

**Issue by Oasis-Git** [tgale96/grouped_gemm#15]
Hi, I am currently running into an error. The grouped_gemm could perform on tensors on device:0 but fails on device:1. Do you have any idea about this error? Thanks.

Here is one example code.
```
from grouped_gemm import ops
import torch

num_expert = 15
expert_input_dim = 1000
expert_output_dim = 500

expert_parameters = torch.randn(num_expert, expert_input_dim, expert_output_dim, dtype=torch.bfloat16)
expert_parameters = expert_parameters.to("cuda:1")

input_dim = 1000

input = torch.randn(8235, input_dim, dtype=torch.bfloat16)

selected_expert = torch.tensor([578, 578, 596, 371, 612, 564, 558, 481, 492, 489, 591, 474, 455, 607,
        789])
selected_expert = selected_expert.to(torch.int64)
input = input.to("cuda:1")

output = ops.gmm(input, expert_parameters, selected_expert, False)
print(output)
```

**Comment by tgale96** [comment]
Hi! Could you share more details about the error you're seeing?

**Comment by Oasis-Git** [comment]
Hi. Thanks for your reply. Here is the error.
```
Traceback (most recent call last):
  File "/home/yuweia/MoE-Inference/test/group_gemm.py", line 20, in <module>
    output = ops.gmm(input, expert_parameters, selected_expert, False)
  File "/home/anaconda3/envs/yuweia/lib/python3.10/site-packages/grouped_gemm/ops.py", line 33, in gmm
    return GroupedGemm.apply(a, b, batch_sizes, trans_b)
  File "/home/anaconda3/envs/yuweia/lib/python3.10/site-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/anaconda3/envs/yuweia/lib/python3.10/site-packages/grouped_gemm/ops.py", line 11, in forward
    return backend.gmm(a, b, batch_sizes, trans_a=False, trans_b=trans_b)
  File "/home/anaconda3/envs/yuweia/lib/python3.10/site-packages/grouped_gemm/backend.py", line 27, in gmm
    backend.gmm(a, b, c, batch_sizes, trans_a, trans_b)
RuntimeError: CuBLAS Error
```

**Comment by imoneoi** [comment]
It's likely an issue of torch CUDA extension. Try setting the CUDA device ID before running the program.

```python
import torch
torch.cuda.set_device(1)
```
